# Generated by Django 5.0 on 2023-12-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_addmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmodel',
            name='date',
            field=models.DateTimeField(default=0, verbose_name='xx-xx-xxxx'),
            preserve_default=False,
        ),
    ]
