# Generated by Django 5.0 on 2023-12-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_addmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmodel',
            name='date',
        ),
    ]
